#GUI constants

TOTAL_NUMBER_SIGNS = 43

DEMO_ID_1 = 1
DEMO_ID_2 = 2

DISCREEN_ROWS = 10
DISCREEN_COLUMNS = 7

RESULT_SCREEN_ROWS = 9

PERCENTAGE_GREEN_TO_YELLOW = 5
PERCENTAGE_YELLOW_TO_RED = 10

#GUI Sizes
WINDOW_SIZE_RATIO = 0.65
INFOSCREEN_SIZE_RATIO = 0.75

PIXMAP_SCALE_WIDTH = 790
PIXMAP_SCALE_HEIGTH = 410

BLUEBUTTONBIG_WIDTH = 350
BLUEBUTTONBIG_HEIGTH = 220

BLUEBUTTONSMALL_WIDTH = 220
BLUEBUTTONSMALL_HEIGTH = 40

SMALLBUTTON_WIDTH = 55
SMALLBUTTON_HEIGTH = 55

INFO_BUTTON_WIDTH = 140
INFO_BUTTON_HEIGTH = 45
INFO_ICON_WIDTH = 130
INFO_ICON_HEIGTH = 30

BACK_BUTTON_WIDTH = 40
BACK_BUTTON_HEIGTH = 40
BACK_ICON_WIDTH = 20
BACK_ICON_HEIGTH = 20

DATA_ARRAY_SIGN_ID = 0
DATA_ARRAY_SIGN_INPUT = 1
DATA_ARRAY_SIGN_DETECTED = 2
DATA_ARRAY_COLUMN_COUNT = 3

DEMODATA_CSV_SIGN_ID = 0
DEMODATA_CSV_SIGN_COUNT = 2

POPUP_MESSAGE_WIDHT = 600
POPUP_MESSAGE_HEIGHT = 200

GRAPHICS_PREVIEW_WIDTH = 800
GRAPHICS_PREVIEW_HEIGTH = 420

SIGN_WIDTH = 48
SIGN_HEIGTH = 48

SIGN_COUNT_WIDTH = 40
SIGN_COUNT_HEIGTH = 30

SPINBOX_WIDTH = 50
SPINBOX_HEIGTH = 25

ANALYZE_SCREEN_ICON_WIDTH = 75
ANALYZE_SCREEN_ICON_HEIGTH = 75

RESULT_SCREEN_PERCENTAGE_WIDTH = 80
RESULT_SCREEN_PERCENTAGE_HEIGTH = 80

RESULT_SCREEN_HEADER_WIDTH = 80
RESULT_SCREEN_HEADER_HEIGTH = 30

SCROLLAREA_INNER_WIDTH = 950
SCROLLAREA_OUTER_MIN_WIDTH = 976
SCROLLAREA_OUTER_MAX_WIDTH = 1020
SCROLLAREA_MIN_HEIGTH = 0
SCROLLAREA_MAX_HEIGTH = 16777215

HEADLINE_SPACING = 6

#Screen-ID´s
START_SCREEN = 0
DEMO_SCREEN = 1
PREVIEW_SCREEN = 2
DI_SCREEN = 3
ANALYZE_PV_SCREEN = 4
ANALYZE_SCREEN = 5
DEMO_DATA_SCREEN = 6
RESULT_SCREEN = 7
INFO_SCREEN = 8